### ISSUE TITLE
跟 antd 学动画 - Button

### ISSUE THREAD

**Issue by yshaojun** [yshaojun/blog#12]
在前端开发中，适当的动画能使过渡更加自然，并增强操作反馈，因此打算跟 antd 系统地学一学，本文介绍 Button 点击时的波动效果。

## 源码解读

首先找到 Button 组件位置 components/button/button.tsx，在 `render` 函数里，看到这句：

```tsx
return <Wave>{buttonNode}</Wave>;
```

看来波动效果完全在父组件 `Wave` 里实现的，进入 components/_util/wave.tsx 里，先看 `render`：

```tsx
renderWave = ({ csp }: ConfigConsumerProps) => {
  const { children } = this.props;
  this.csp = csp;

  return children;
};

render() {
  return <ConfigConsumer>{this.renderWave}</ConfigConsumer>;
}
```

`ConfigConsumer` 是使用 React context 的 `Consumer`，用来接收最顶层的配置，不用理它，而 `renderWave` 里返回的是子组件，说明 `render` 函数并不参与动画实现。

顺着 React 生命周期，于是去看 `componentDidMount`：

```tsx
componentDidMount() {
  const node = findDOMNode(this) as HTMLElement;
  if (!node || node.nodeType !== 1) {
    return;
  }
  this.instance = this.bindAnimationEvent(node);
}
```

这里对组件对应的 DOM 执行了 `bindAnimationEvent` 操作，在 `bindAnimationEvent` 里，对 DOM 绑定了 `click` 事件：

```tsx
node.addEventListener('click', onClick, true);
return {
  cancel: () => {
    node.removeEventListener('click', onClick, true);
  },
};
```

返回一个 `cancel` 给调用者，有点 React hooks 中 `useEffect` 的意思。这个 `onClick` 主要做了如下几件事：

1. 处理 Radio
2. 停止动画（连续点击时前面未结束的动画）；
3. 获取波动颜色（waveColor）；
4. 异步执行了 `this.onClick` 函数。

在 `this.onClick` 中，忽略各种边界，可以看到：

```tsx
const attributeName = this.getAttributeName();

// 此处省略一些代码

styleForPesudo.innerHTML = `
[ant-click-animating-without-extra-node='true']::after, .ant-click-animating-node {
  --antd-wave-shadow-color: ${waveColor};
}`;
if (!document.body.contains(styleForPesudo)) {
  document.body.appendChild(styleForPesudo);
}
```

原来是在 body 里用 style 标签插入了一段样式。全局搜索，找到这段样式在 **components/style/core/motion/other.less** 里。

```less
// 此处省略一些代码

[ant-click-animating-without-extra-node='true']::after,
.ant-click-animating-node {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  display: block;
  border-radius: inherit;
  box-shadow: 0 0 0 0 @primary-color;
  box-shadow: 0 0 0 0 var(--antd-wave-shadow-color);
  opacity: 0.2;
  animation: fadeEffect 2s @ease-out-circ, waveEffect 0.4s @ease-out-circ;
  animation-fill-mode: forwards;
  content: '';
  pointer-events: none;
}

@keyframes waveEffect {
  100% {
    box-shadow: 0 0 0 @primary-color;
    box-shadow: 0 0 0 @wave-animation-width var(--antd-wave-shadow-color);
  }
}

@keyframes fadeEffect {
  100% {
    opacity: 0;
  }
}
```

所以，antd 的 button wave 是 **在点击时添加伪元素，这个伪元素通过 `box-shadow` 和 `animation` 实现了波动效果**。

## 自行实现

从读源码的感受而言，antd `Wave` 实现比较繁琐，有很多“莫名其妙”的 `resetEffect`，且有第三方依赖。按照这个思路，我改写了一个零依赖的组件如下：

```tsx
/**
 * Wave/index.tsx
 */
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import './index.css'

let styleNode: HTMLStyleElement | null = null;

export default class Wave extends React.Component {
  node: HTMLElement | null = null
  timeId: number = 0

  componentDidMount () {
    this.node = ReactDOM.findDOMNode(this) as HTMLElement
    this.node.addEventListener('click', this.bindEffect, true)
  }

  componentWillUnmount () {
    this.node.removeEventListener('click', this.bindEffect, true)
  }

  bindEffect = () => {
    this.stopEffect();
    this.startEffect();
  }

  startEffect = () => {
    if (!styleNode) {
      styleNode = document.createElement('style');
    }

    const waveColor = (
      getComputedStyle(this.node).getPropertyValue('border-top-color') ||
      getComputedStyle(this.node).getPropertyValue('background-color')
    )

    styleNode.innerHTML = `
    [data-__wave='true']::after {
      --wave-shadow-color: ${waveColor};
    }`;

    if (!document.body.contains(styleNode)) {
      document.body.appendChild(styleNode);
    }

    this.node.setAttribute('data-__wave', 'true')
  }

  stopEffect = () => {
    this.node.setAttribute('data-__wave', 'false')
  }

  render () {
    return this.props.children;
  }
}
```

```css
/**
 * Wave/index.css
 *
 * 照抄了 antd 的 css
 */
html {
  --wave-shadow-color: transparent;
}

[data-__wave ='true'] {
  position: relative;
}

[data-__wave ='true']::after,
.ant-click-animating-node {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  display: block;
  border-radius: inherit;
  box-shadow: 0 0 0 0 var(--wave-shadow-color);
  opacity: 0.2;
  animation: __fadeEffect 2s cubic-bezier(0.08, 0.82, 0.17, 1), __waveEffect 0.4s cubic-bezier(0.08, 0.82, 0.17, 1);
  animation-fill-mode: forwards;
  content: '';
  pointer-events: none;
}

@keyframes __waveEffect {
  100% {
    box-shadow: 0 0 0 6px var(--wave-shadow-color);
  }
}

@keyframes __fadeEffect {
  100% {
    opacity: 0;
  }
}
```

和 antd Button 波动效果基本相同。
